controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # joint3_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - torso_2_joint
      - torso_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# joint3_trajectory_controller:
#   ros__parameters:
#     joints:
#       - torso_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity      