controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: true

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["fr_caster_rotation_joint", "fl_caster_rotation_joint"]

tricycle_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [fl_caster_r_wheel_joint, fr_caster_r_wheel_joint]
    front_wheels_names: [b_caster_rotation_joint]

    # Model
    wheelbase: 0.37266  # 0.12422+0.24844
    wheel_track: 0.4303 # 0.21515*2
    front_wheels_radius: 0.0782
    rear_wheels_radius: 0.0782

    # Odometry
    odom_frame_id: base_footprint
    base_frame_id: base_link
    