/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    flip3: false
    inverse1: true
    inverse2: true
    inverse3: true
    laser1Alpha: 0.0
    laser1AngleMax: 94.0
    laser1AngleMin: -4.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: -0.3
    laser1YOff: -0.475
    laser1ZOff: 0.176
    laser2Alpha: 180.0
    laser2AngleMax: 94.0
    laser2AngleMin: 0.0
    laser2B: 255
    laser2G: 0
    laser2R: 0
    laser2XOff: 0.3
    laser2YOff: 0.475
    laser2ZOff: 0.176
    laser3Alpha: 180.0
    laser3AngleMax: 94.0
    laser3AngleMin: 0.0
    laser3B: 0
    laser3G: 255
    laser3R: 0
    laser3XOff: 0.3
    laser3YOff: 0.475
    laser3ZOff: 0.176
    pointCloudTopic: cloud_in
    pointCloutFrameId: laser
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /base_laser_front/scan_raw
    scanTopic2: /base_laser_left/scan_raw
    scanTopic3: /base_laser_right/scan_raw
    show1: true
    show2: true
    show3: true
    use_sim_time: false

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0087
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 10.0
    range_min: 0.35
    scan_time: 0.3333
    target_frame: laser
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
