controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: true

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["right_wheel_joint", "left_wheel_joint"]

tricycle_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [right_wheel_joint, left_wheel_joint]
    front_wheels_names: [steering_joint]

    # Model
    wheelbase: 1.7
    wheel_track: 1.0
    front_wheels_radius: 0.3
    rear_wheels_radius: 0.3

    # Odometry
    odom_frame_id: odom
    base_frame_id: base_link
    
